service: gingr-webhook
frameworkVersion: '3'
	
plugins:
  - serverless-api-gateway-throttling
  - serverless-plugin-typescript
  - serverless-stage-manager
custom:
  # Configures throttling settings for the API Gateway stage
  # They apply to all http endpoints, unless specifically overridden
  apiGatewayThrottling:
    maxRequestsPerSecond: 100
    maxConcurrentRequests: 10
  stages:
    - dev
    - prod
  airtableBaseId:
    dev: appkIVEko9VyjkIVP
    prod: appd02u10BuFuz904


provider:
  name: aws
  runtime: nodejs14.x
  deploymentMethod: direct
  stage: ${opt:stage,'dev'}

functions:
  handleEvent:
    handler: src/handler.handleWebhook
    environment: 
      AIRTABLE_API_KEY: ${ssm:/gingr-webhooks/airtable-api-key}
      WEBHOOK_SIGNATURE_KEY: ${ssm:/gingr-webhooks/webhook-signature-key}
      GINGR_API_KEY: ${ssm:/gingr-webhooks/gingr-api-key}
      AIRTABLE_BASE_ID: ${self:custom.airtableBaseId.${self:provider.stage}}
    events:
      - httpApi:
          path: /
          method: post

  syncData:
    handler: src/handler.scheduledSync
    environment: 
      AIRTABLE_API_KEY: ${ssm:/gingr-webhooks/airtable-api-key}
      GINGR_API_KEY: ${ssm:/gingr-webhooks/gingr-api-key}
      AIRTABLE_BASE_ID: ${self:custom.airtableBaseId.${self:provider.stage}}
    events:
      - schedule:
          name: sync-data
          description: 'sync data every 5 minutes'
          rate: cron(*/5 * * * ? *)
    