service: gingr-webhook
frameworkVersion: '3'
	
plugins:
  - serverless-api-gateway-throttling

custom:
  # Configures throttling settings for the API Gateway stage
  # They apply to all http endpoints, unless specifically overridden
  apiGatewayThrottling:
    maxRequestsPerSecond: 100
    maxConcurrentRequests: 10

provider:
  name: aws
  runtime: nodejs14.x
  deploymentMethod: direct
  stage: prod

functions:
  handleEvent:
    handler: handler.handleEvent
    environment: 
      AIRTABLE_API_KEY: ${ssm:/gingr-webhooks/airtable-api-key}
      WEBHOOK_SIGNATURE_KEY: ${ssm:/gingr-webhooks/webhook-signature-key}
    events:
      - httpApi:
          path: /
          method: post
